MVideo/urls.py
from django.contrib import admin
from django.urls import path, include
from Menu.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Menu.urls')),
    path('index/', index),
    path('accounts/', include('allauth.urls')),
]

Menu/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'lista'
urlpatterns = [
    path('', category),
    path('product/', product, name='product'),
    path('make_pr/', ProductView.as_view(), name='make_pr'),
    path('pro/', ProductList.as_view(), name='pro'),
    path('make/', ProductView.as_view(), name='make'),

]

Menu/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
"""Product FK Category and through Category to Subcategory 
Category name
Subcategory name"""


class MenuItem(MPTTModel):
    name = models.CharField(max_length=100, unique=True)
    url = models.CharField('Ссылка', max_length=255)
    position = models.PositiveIntegerField('Позиция', default=1)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['position']

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Пункт меню'
        verbose_name_plural = 'Пункты меню'


class Product(models.Model):
    name = models.CharField(max_length=250, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    categories = models.ManyToManyField('Category', through="ProductCategory")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class ProductCategory(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.category}/{self.product}'

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'

Menu/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.edit import FormMixin
from .models import *
from django.views.generic.list import ListView
from django.views import View
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from dotenv import load_dotenv
import os
load_dotenv()

def index(request):
    menu = MenuItem.objects.all()
    return render(request, 'base.html', {'menu': menu})

def category(request):
    return HttpResponse('<h1>Категория</h1>')


def product(request):
    return HttpResponse('<h1>Продукты</h1>')


class ProductList(ListView):
    model = Product
    template_name = 'base.html'
    context_object_name = 'pro'


class CategoryList(ListView):
    model = Category
    template_name = 'make_pr.html'
    context_object_name = 'category'


class ProductView(View):
    def get(self, request, *args, **kwargs):
        category = Category.objects.all()
        return render(request, 'make_pr.html', {'category': category})
    def post(self, request, *args, **kwargs):
        product = Product(
            name=request.POST['name_product'],
            description=request.POST['description_product']
        )
        product.save()
        product.categories.add(request.POST['categories'])
        html_content = render_to_string('product_created.html',
                                        {
                                            'product': product,
                                        })
        msg = EmailMultiAlternatives(
            subject=f'Добавлен новый товар!! Смотри!',
            body=product.description,
            from_email=os.getenv("email_e"),
            to=['des079@inbox.ru']
        )
        msg.attach_alternative(html_content, "text/html")
        msg.send()
        return redirect('lista:product')

Menu/templates/base.html
{% load common_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
BASE
{% show_menu %}
{% for p in pro %}
Название товара:{{ p.name }}
<br>
Описание:{{ p.description }}
<hr>
{% endfor %}
d
</body>
</html>

Menu/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>INDEX PAGE</h1>
</body>
</html>

Menu/templates/make_pr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Product</title>
</head>
<body>
<h1>Make product</h1>
<form action="{% url 'lista:make_pr' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="name_product">Products name</label>
    <input type="text" name="name_product"><br>
    <label for="description_product">Description of the product</label><br>
    <input type="text" name="description_product"><br>
    <label for="categories">Category of the product</label><br>
    <input list="cat" name="categories">
    <datalist id="cat">
        {% for cat in category %}
        <option value={{cat.id}}>{{cat.name}}</option>
        {% endfor %}
    </datalist>
    <br>
    <input type="submit">
</form>

</body>
</html>

Menu/templates/menu.html
{% for mem in menu0 %}
{% if mem.get_children %}
<li class="nav-iten dropdown">
    <a class="nav-link dropdown-toggle" href="#">{{ mem }}</a>
    <ul class="dropdown-menu" aria-labelledby="dropdown03">
                {% for m1 in mem.get_children %}
                {% if m1.get_children %}
                    <li class="nav-iten dropdown">
                        <a class="nav-link dropdown-toggle" href="#">{{ m1 }}</a></ul>
                        <ul class="dropdown-menu" aria-labelledby="dropdown03">
                            {% for m2 in m1.get_children %}
                            {% if m2.get_children %}
                            <ul><li class="nav-iten dropdown">
                                <a class="nav-link dropdown-toggle" href="#">{{ m2 }}</a></ul></ul>
                                <ul class="dropdown-menu" aria-labelledby="dropdown03">
                                    {% for m3 in m2.get_children %}
                                    {% if m3.get_children %}
                            <ul><ul><li class="nav-iten dropdown">
                                <a class="nav-link dropdown-toggle" href="#">{{ m3 }}</a></ul></ul></ul>
                                <ul class="dropdown-menu" aria-labelledby="dropdown03">
                                    {% else %}
                                    <ul><ul><li><a class="dropdown-item" href="#">{{ m3 }}</a></li></ul></ul>
                                    {% endif %}
                                    {% endfor %}

                                    {% else %}
                                    <ul><li><a class="dropdown-item" href="#">{{ m2 }}</a></li></ul>
                                    {% endif %}
                                    {% endfor %}
                {% else %}
                        <li><a class="dropdown-item" href="#">{{ m1 }}</a></li>
                        {% endif %}
        {% endfor %}
        {% else %}
                <li><a class="dropdown-item" href="#">{{ m_m }}</a></li>
                {% endif %}
        {% endfor %}
    </ul>
</li>

Menu/templates/product_created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,intitiial-scale=10">
    <title>Document</title>
</head>
<body>
<h2>Добавлен товар: {{ product.name }}.</h2>
<p>Название: {{ product.name }} {{product.categories}}<br>
Описание: {{ product.description }}</p>
</body>
</html>

Menu/templates/tree_menu.html
{% load common_tags %}

{% ifequal menu_type "unordered-list" %}
    <ul>
        {% for menu_item in menu.root_item.children %}
            {% show_menu_item menu_item %}
        {% endfor %}
    </ul>
{% endifequal %}
{% ifequal menu_type "ordered-list" %}
    <ol>
        {% for menu_item in menu.root_item.children %}
            {% show_menu_item menu_item %}
        {% endfor %}
    </ol>
{% endifequal %}